#!/bin/bash

create_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        mkfifo $1
        shift 1
    done
}

delete_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        shift 1
    done
}

if [ -z $DISPLAY ] ; then export DISPLAY=:0 ; fi

shmem=shmem.corestate
stderr=stderr.corestate
vcd=vcd.corestate
fifos="$stderr $vcd $shmem"
create_fifos $fifos

cleanup () {
    delete_fifos $fifos
    exit
}

trap "cleanup" INT

build/linux-release/qamar 1>$vcd 2>$stderr &
./corestate.lua <$stderr &
shmidcat <$vcd >$shmem 2>/dev/null &
gtkwave -v -I display.gtkw -g -O /dev/null $@ <$shmem
kill $(jobs -p)
cleanup
