#!/bin/bash

create_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        mkfifo $1
        shift 1
    done
}

delete_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        shift 1
    done
}

if [ -z $DISPLAY ] ; then export DISPLAY=:0 ; fi

run () {
    shmem=shmem.corestate
    stderr=stderr.corestate
    vcd=vcd.corestate
    fifos="$stderr $vcd $shmem"
    create_fifos $fifos

    local enable_gui=1
    while [ $# -gt 0 ]; do
        if [ $1 = "--nogui" -o $1 = "-n" ]; then enable_gui=0;shift 1
        else return 1
        fi
    done

    local PID=
    cleanup () {
        kill -- $PID
        delete_fifos $fifos
    }
    
    trap "cleanup" INT
    
    ./corestate.lua <$stderr &
    PID="$! $PID"
    if [ $enable_gui -gt 0 ] ; then 
        shmidcat <$vcd >$shmem 2>/dev/null &
        PID="$! $PID"
        build/linux-release/qamar 1>$vcd 2>$stderr &
        PID="$! $PID"
        gtkwave -v -I display.gtkw -g -O /dev/null <$shmem
    else
        build/linux-release/qamar 1>/dev/null 2>$stderr
    fi
    cleanup
}

run $@
