#!/bin/bash

create_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        mkfifo $1
        shift 1
    done
}

delete_fifos () {
    while [ $1 ];
    do
        rm -rf $1
        shift 1
    done
}

if [ -z $DISPLAY ] ; then export DISPLAY=:0 ; fi

run () {
    shmem=shmem.corestate
    stderr=stderr.corestate
    vcd=vcd.corestate
    fifos="$stderr $vcd $shmem"
    create_fifos $fifos
    
    local PID=
    cleanup () {
        kill -- $PID
        delete_fifos $fifos
    }
    
    trap "cleanup" INT
    
    build/linux-release/qamar 1>$vcd 2>$stderr &
    PID="$! $PID"
    shmidcat <$vcd >$shmem 2>/dev/null &
    PID="$! $PID"
    ./corestate.lua <$stderr &
    PID="$! $PID"
    gtkwave -v -I display.gtkw -g -O /dev/null $@ <$shmem
    cleanup
}

run $@
